version: "3.7"
services:

  app:
    container_name: paak_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: on-failure
    environment:
      - DB_HOST=postgres
      - SERVICE_REST_PORT=8051
    ports:
      - 8051:8051
    volumes:
      - ./:/app
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    container_name: paak_postgres
    image: postgres:13
    environment:
      DATABASE_HOST: "${DB_HOST}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
